# -*- coding: utf-8 -*-
"""Estadistica

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1esbfu8eh9dpZ7D1kd680Twaul-Tc8OxZ
"""

import math
import random

# Generar una lista de 100 números entre 1 y 10 con máximo 2 decimales
lista = [round(random.uniform(1, 10), 2) for _ in range(100)]

xMin = min(lista)
xMax = max(lista)
tamañoMuestra = len(lista)
rango = xMax - xMin
numIntervalos = math.ceil(1 + (3.3 * math.log(tamañoMuestra)))
amplitud = rango / numIntervalos
print(f'minimo = {xMin}     maximo = {xMax}')
print(f'Tamaño de muestra: {tamañoMuestra}')
print(f'Rango: {round(rango, 2)}')
print(f'Num intervalos: {numIntervalos}')
print(f'Amplitud: {amplitud}')
print('---------------------------------------------------------------------------------------------------')

print('Construyedo tabla')
print('---------------------------------------------------------------------------------------------------')
print('INTERVALOS                 xi         fi        Fi')
print('---------------------------------------------------------------------------------------------------')

sumaXF = 0
Fi = 0
for i in range(numIntervalos):
  limInferior = xMin + i * amplitud
  limSuperior = xMin + (i + 1) * amplitud
  marcaClase = (limInferior + limSuperior)/2
  fi = 0
  if i == numIntervalos - 1:
      for d in lista:
          if d >= limInferior and d <= limSuperior:
              fi += 1
  else:
      for d in lista:
         if d >= limInferior and d < limSuperior:
            fi += 1
  xf = fi * marcaClase
  sumaXF += xf
  Fi += fi
  intervalo = f'[{round(limInferior, 2)} ; {round(limSuperior, 2)}>'
  print(f'{intervalo}            {round(marcaClase, 3)}          {fi}          {Fi}')

media = sumaXF /  tamañoMuestra
print('\n', f'Media: {round(media, 4)}')




'''cuartiles para datos no agrupados. '''
import random
datos = [round(random.uniform(1, 10), 2) for _ in range(100)]
print('datos: ',datos)

listaOrdenada = sorted(datos)
cantidadElementos = len(datos)
print('ordenados: ',listaOrdenada,'\n')

cuartiles = (1, 2, 3)
for k in cuartiles:
  posicion = k * (cantidadElementos + 1) / 4
  if isinstance(posicion, int):
    print(f'El cuartil {k} es: {listaOrdenada[posicion - 1]}')
  else:
    parteEntera = int(posicion)
    parteDecimal = posicion - parteEntera
    valorPosicionA = listaOrdenada[parteEntera - 1]
    valorPosicionB = listaOrdenada[parteEntera]
    percentil = valorPosicionA + parteDecimal * (valorPosicionB - valorPosicionA)
    print(f'El cuartil {k} es: {percentil}')